# Generated by Django 4.0 on 2021-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.PositiveSmallIntegerField()),
                ('variant', models.CharField(max_length=80)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
            ],
        ),
    ]
