# Generated by Django 4.0 on 2021-12-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.question'),
        ),
    ]
