# Generated by Django 4.0 on 2021-12-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_alter_choices_qid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='qid',
            new_name='quest',
        ),
    ]
