# Generated by Django 4.0 on 2021-12-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_question_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
