# Generated by Django 4.0 on 2021-12-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restapp', '0005_delete_choices_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('points', models.IntegerField(default=5)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choiceid', models.AutoField(primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=80)),
                ('status', models.BooleanField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.question')),
            ],
        ),
    ]
