# Generated by Django 4.0 on 2021-12-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
