# Generated by Django 4.0 on 2021-12-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_rename_choices_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='game',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
